### ISSUE TITLE
Harpoon Toggle File Menu doesn't allow for quick hopping

### ISSUE THREAD

**Issue by DominikMendel** [otavioschwanck/harpoon.el#3]
Hi there, I just started using your package and it is fantastic. Much appreciated! 

This might be a feature request more than a bug, but the only thing I noticed was when you are editing the `harpoon-toggle-file` you actually cannot jump to the files from that buffer with `harpoon-go-to-1`. It appears you have to close the buffer before you can perform the `harpoon-go-to-1`; even if the buffer is saved and hasn't been edited. 

Steps: 
1. Save a harpoon file
2. Save another
3. Open harpoon-toggle-file
4. Attempt to harpoon-go-to-1 or harpoon-go-to-2. This doesn't work. 
5. Close the buffer. 
6. Now you can harpoon-go-to-1/2

**Comment by otavioschwanck** [comment]
Hi @DominikMendel 

Thanks for reporting!

Fixed: https://github.com/otavioschwanck/harpoon.el/commit/9bbca44630cd23dda8595e13f8d3cc9af28c85db
